version: 2

build:
    image: latest
    
python:
  version: 3.6
  setup_py_install: true
  install:
      - requirements: requirements.txt'
      - requirements: docs/requirements.txt'

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true