version: 2

python:
  version: 3.6
  install:
      - requirements: ['requirements.txt', 'docs/requirements.txt']
      - method: setuptools
        path: .
   system_packages: true

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true